FROM ubuntu:18.04

LABEL maintainer="814980678@qq.com"
RUN apt update -y && apt upgrade -y 
# COPY sources.list /etc/apt/sources.list
RUN apt update -y && apt install -y nodejs python3.6 g++ gcc ocaml ghc fpc openjdk-8-jdk openjdk-8-jre

